auth-server:
  client:
    clientId: x
    clientSecret: x
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user